[UI]
enableRichToolTips = false

[HTTPServer]
enabled = true
addr = "localhost"
port = 12321
useIpv6 = true

[GHub]
enabled = false

[Native]
enabled = true

# Time in seconds to retry a device poll on failure
retryTime = 10

# Time in seconds until the next device poll on success
pollPeriod = 600

# List of disabled devices
disabledDevices = [
]
