using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text.Json;

namespace LGSTrayUI;

public sealed class LocalizationService : ObservableObject
{
    private readonly UserSettingsWrapper _settings;

    public LocalizationService(UserSettingsWrapper settings)
    {
        _settings = settings;
        _settings.PropertyChanged += (_, e) =>
        {
            if (e.PropertyName == nameof(UserSettingsWrapper.Language))
            {
                OnPropertyChanged("Item[]");
                OnPropertyChanged(nameof(CurrentLanguage));
            }
        };
    }

    public string CurrentLanguage => _settings.Language;

    public string this[string key] => Translate(key);

    internal static IReadOnlyDictionary<string, string> GetCatalogForTesting(string language) =>
        GetCatalog(language);

    internal static string TranslateBootstrap(string key)
    {
        string language = CultureInfo.CurrentUICulture.Name;
        try
        {
            if (File.Exists(PowerTrayConstants.SettingsPath))
            {
                using JsonDocument settings = JsonDocument.Parse(File.ReadAllText(PowerTrayConstants.SettingsPath));
                if (settings.RootElement.TryGetProperty("Language", out JsonElement languageElement) &&
                    languageElement.ValueKind == JsonValueKind.String &&
                    !string.IsNullOrWhiteSpace(languageElement.GetString()))
                {
                    language = languageElement.GetString()!;
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException)
        {
            // Bootstrap localization is best effort because this path is used to
            // report a different startup-settings failure.
        }

        IReadOnlyDictionary<string, string> catalog = GetCatalog(language);
        return catalog.TryGetValue(key, out string? value)
            ? value
            : EnUs.TryGetValue(key, out string? fallback) ? fallback : key;
    }

    public string Translate(string key)
    {
        IReadOnlyDictionary<string, string> dict = GetCatalog(_settings.Language);

        return dict.TryGetValue(key, out string? value)
            ? value
            : EnUs.TryGetValue(key, out string? fallback) ? fallback : key;
    }

    private static IReadOnlyDictionary<string, string> GetCatalog(string language)
    {
        return language switch
        {
            string value when value.StartsWith("zh", StringComparison.OrdinalIgnoreCase) => ZhCn,
            string value when value.StartsWith("ja", StringComparison.OrdinalIgnoreCase) => JaJp,
            _ => EnUs,
        };
    }

    private static readonly IReadOnlyDictionary<string, string> EnUs = new Dictionary<string, string>
    {
        ["ProductName"] = "PowerTray",
        ["MenuDevices"] = "Devices",
        ["MenuRediscover"] = "Rescan devices",
        ["MenuNumericIcon"] = "Show numeric battery icon",
        ["MenuAutoStart"] = "Start with Windows",
        ["MenuSettings"] = "Settings",
        ["MenuCheckUpdates"] = "Check for updates",
        ["MenuExit"] = "Exit",
        ["SettingsTitle"] = "PowerTray Settings",
        ["NavGeneral"] = "General",
        ["NavAlerts"] = "Alerts",
        ["NavDevices"] = "Devices",
        ["NavDiagnostics"] = "Diagnostics",
        ["Language"] = "Language",
        ["English"] = "English",
        ["Chinese"] = "Simplified Chinese",
        ["Japanese"] = "Japanese",
        ["Theme"] = "Theme",
        ["ThemeSystem"] = "System",
        ["ThemeLight"] = "Light",
        ["ThemeDark"] = "Dark",
        ["UiScale"] = "Interface size",
        ["UiScaleSmall"] = "Small",
        ["UiScaleStandard"] = "Standard",
        ["UiScaleLarge"] = "Large",
        ["UiScaleMaximum"] = "Maximum",
        ["StartWithWindows"] = "Start with Windows",
        ["AutoCheckUpdates"] = "Check for updates automatically",
        ["NumericIcon"] = "Show battery percentage in the tray icon",
        ["TrayToolTipDisplay"] = "Tray hover display",
        ["TrayToolTipModeDisabled"] = "Disable hover display",
        ["TrayToolTipModeWindowsNative"] = "Windows native hover",
        ["TrayToolTipModePowerTrayCustom"] = "PowerTray custom hover",
        ["TrayToolTipDescription"] = "Windows native hover is managed by the system tray, so its appearance and display time follow Windows. PowerTray custom hover supports the application theme and complete information. Changing the hover implementation requires recreating the tray icons and therefore takes effect after PowerTray restarts.",
        ["TrayToolTipRestartPending"] = "Takes effect after restart",
        ["TrayToolTipRestartTitle"] = "Restart PowerTray required",
        ["TrayToolTipRestartBody"] = "The tray hover display mode takes effect after the tray icons are recreated. Restart PowerTray now?",
        ["TrayToolTipRestartDetail"] = "Native hover is managed by Windows Shell, while custom hover is managed by WPF Popup. Restarting fully clears the previous tray registration, Popup, and event subscriptions, preventing overlapping hover displays or a remnant in the top-left corner of the screen.",
        ["RestartNow"] = "Restart now",
        ["RestartLater"] = "Restart later",
        ["RestartFailedTitle"] = "PowerTray restart failed",
        ["RestartFailedBody"] = "The new PowerTray process could not be started. The current PowerTray instance will keep running, and the saved hover mode will take effect on the next normal start.",
        ["FollowGlobalNumericIcon"] = "Use global tray-icon display style",
        ["ConfirmForgetDeviceTitle"] = "Forget this device?",
        ["ConfirmForgetDeviceBody"] = "This will remove saved settings and history for {0}. Continue?",
        ["GlobalDefaults"] = "Default alert settings",
        ["DefaultThreshold"] = "Default low-battery threshold",
        ["WindowsNotification"] = "Windows notifications",
        ["TrayBlink"] = "Blink tray icon",
        ["QuietHours"] = "Quiet hours",
        ["QuietHoursEnabled"] = "Enable quiet hours",
        ["QuietStart"] = "Start",
        ["QuietEnd"] = "End",
        ["SuppressFullscreen"] = "Pause Windows notifications while a full-screen app is active",
        ["DeviceAlerts"] = "Device alerts",
        ["Alias"] = "Custom device name",
        ["AliasHint"] = "Leave blank to use the device's original name.",
        ["OriginalName"] = "Original name",
        ["Offline"] = "Offline",
        ["Threshold"] = "Threshold",
        ["LowBatteryThreshold"] = "Low-battery alert threshold",
        ["FollowGlobalThreshold"] = "Use default threshold",
        ["Pause"] = "Pause",
        ["PauseOneHour"] = "Pause for 1 hour",
        ["PauseUntilNextLaunch"] = "Pause until next launch",
        ["ResumeAlerts"] = "Resume alerts",
        ["TestNotification"] = "Test notification",
        ["TestBlink"] = "Test tray-icon blink",
        ["StopBlink"] = "Stop blinking",
        ["RestoreDefaults"] = "Restore defaults",
        ["RemoveHistory"] = "Forget this device",
        ["LastUpdate"] = "Last updated",
        ["Battery"] = "Battery",
        ["BatteryUnknown"] = "Battery unknown",
        ["BatteryStatusCharging"] = "Charging",
        ["BatteryStatusFull"] = "Fully charged",
        ["BatteryStatusNotCharging"] = "Not charging",
        ["BatteryStatusDischarging"] = "Discharging",
        ["BatteryStatusUnknown"] = "Status unknown",
        ["NoDevices"] = "No supported Logitech devices found yet.",
        ["Diagnostics"] = "Diagnostics",
        ["ExportDiagnostics"] = "Export diagnostics",
        ["RefreshDiagnostics"] = "Refresh",
        ["GHubStatus"] = "G Hub running",
        ["Port9010Status"] = "G Hub local service reachable",
        ["CurrentLanguage"] = "Current language",
        ["AlertSummary"] = "Alert summary",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["LowBatteryTitle"] = "Low battery warning",
        ["LowBatteryBody"] = "{0} battery is at {1:0}%.",
        ["TestNotificationTitle"] = "PowerTray test notification",
        ["TestNotificationBody"] = "Windows notifications are working for {0}.",
        ["TestNotificationGenericBody"] = "Windows notifications are working.",
        ["SettingsLoadErrorTitle"] = "PowerTray - Settings Error",
        ["SettingsLoadErrorBody"] = "Could not read appsettings.toml. Reset it to defaults?",
        ["DiagnosticsExported"] = "Diagnostics exported",
        ["DiagnosticsExportFailed"] = "Failed to export diagnostics",
        ["CheckingUpdates"] = "Checking for updates...",
        ["AlreadyLatest"] = "PowerTray is up to date.",
        ["UpdateAvailableTitle"] = "Update available",
        ["UpdateAvailableBody"] = "PowerTray {0} is ready to download.",
        ["UpdateAvailableDetail"] = "The installer will be saved to your Downloads folder.",
        ["DownloadingUpdate"] = "Downloading update...",
        ["UpdateDownloadedTitle"] = "Update downloaded",
        ["UpdateDownloadedBody"] = "PowerTray {0} has been downloaded.",
        ["UpdateDownloadedDetail"] = "Saved to {0}",
        ["UpdateDownloadFailed"] = "Could not download the update",
        ["UpdateCheckFailed"] = "Could not check for updates",
        ["HttpRemoteEnabledTitle"] = "Remote HTTP access enabled",
        ["HttpRemoteEnabledBody"] = "PowerTray's device API is listening beyond this PC. Keep the configured access token private and restrict the port with your firewall.",
        ["NoInstallerAsset"] = "The latest release does not include a PowerTray installer.",
        ["UpdateSignatureInvalid"] = "The release checksum signature is invalid.",
        ["UpdateChecksumInvalid"] = "The release checksum file is missing a matching installer filename.",
        ["UpdateChecksumMismatch"] = "The downloaded installer does not match the release checksum.",
        ["DownloadUpdate"] = "Download",
        ["RunInstaller"] = "Run installer",
        ["OpenFolder"] = "Open folder",
        ["Cancel"] = "Cancel",
        ["OK"] = "OK",
        ["Details"] = "Details",
        ["Never"] = "Never",
        ["Available"] = "available",
        ["Unavailable"] = "unavailable",
        ["DiagnosticsTitle"] = "PowerTray Diagnostics",
        ["DiagnosticsGenerated"] = "Generated",
        ["DiagnosticsDevices"] = "Devices",
        ["RecognizedDevices"] = "Recognized devices",
        ["NativeDiagnostics"] = "Native diagnostics: {0}",
        ["NativeDiagnosticsError"] = "Native diagnostics error: {0}",
        ["HidNoResponse"] = "PowerTrayHID did not respond before the diagnostics timeout.",
        ["HidJsonParseFailed"] = "PowerTrayHID returned diagnostics JSON that could not be parsed.",
        ["VersionPrefix"] = "PowerTray version",
        ["ReleaseVersion"] = "Installed version",
        ["PausedUntil"] = "Paused until {0}",
        ["PausedUntilNextLaunch"] = "Paused until next launch",
    };

    private static readonly IReadOnlyDictionary<string, string> ZhCn = new Dictionary<string, string>
    {
        ["ProductName"] = "PowerTray",
        ["FollowGlobalNumericIcon"] = "跟随全局托盘图标显示方式",
        ["ConfirmForgetDeviceTitle"] = "忘记此设备？",
        ["ConfirmForgetDeviceBody"] = "这会删除 {0} 的已保存设置和历史记录。是否继续？",
        ["MenuDevices"] = "设备",
        ["MenuRediscover"] = "重新扫描设备",
        ["MenuNumericIcon"] = "显示数字电量",
        ["MenuAutoStart"] = "开机自启动",
        ["MenuSettings"] = "设置",
        ["MenuCheckUpdates"] = "检查更新",
        ["MenuExit"] = "退出",
        ["SettingsTitle"] = "PowerTray 设置",
        ["NavGeneral"] = "常规",
        ["NavAlerts"] = "提醒",
        ["NavDevices"] = "设备",
        ["NavDiagnostics"] = "诊断",
        ["Language"] = "语言",
        ["English"] = "英语",
        ["Chinese"] = "简体中文",
        ["Japanese"] = "日语",
        ["Theme"] = "主题",
        ["ThemeSystem"] = "跟随系统",
        ["ThemeLight"] = "浅色",
        ["ThemeDark"] = "深色",
        ["UiScale"] = "界面大小",
        ["UiScaleSmall"] = "小",
        ["UiScaleStandard"] = "标准",
        ["UiScaleLarge"] = "大",
        ["UiScaleMaximum"] = "最大",
        ["StartWithWindows"] = "开机自启动",
        ["AutoCheckUpdates"] = "自动检查更新",
        ["NumericIcon"] = "托盘图标显示电量百分比",
        ["TrayToolTipDisplay"] = "托盘悬浮显示",
        ["TrayToolTipModeDisabled"] = "关闭悬浮",
        ["TrayToolTipModeWindowsNative"] = "Windows 原生悬浮",
        ["TrayToolTipModePowerTrayCustom"] = "PowerTray 自定义悬浮",
        ["TrayToolTipDescription"] = "Windows 原生悬浮由系统托盘管理，外观和显示时间跟随 Windows；PowerTray 自定义悬浮支持应用主题和完整信息。切换悬浮实现需要重新创建托盘图标，因此将在重启 PowerTray 后生效。",
        ["TrayToolTipRestartPending"] = "重启后生效",
        ["TrayToolTipRestartTitle"] = "需要重启 PowerTray",
        ["TrayToolTipRestartBody"] = "托盘悬浮显示模式需要在重新创建托盘图标后生效。是否立即重启 PowerTray？",
        ["TrayToolTipRestartDetail"] = "原生悬浮由 Windows Shell 管理，自定义悬浮由 WPF Popup 管理。重启可以确保旧托盘注册、Popup 和事件订阅被完整清理，避免悬浮重叠或残留在屏幕左上角。",
        ["RestartNow"] = "立即重启",
        ["RestartLater"] = "稍后重启",
        ["RestartFailedTitle"] = "PowerTray 重启失败",
        ["RestartFailedBody"] = "无法启动新的 PowerTray 进程。当前 PowerTray 将继续运行，已保存的悬浮模式会在下次正常启动时生效。",
        ["GlobalDefaults"] = "默认提醒设置",
        ["DefaultThreshold"] = "默认低电量提醒阈值",
        ["WindowsNotification"] = "系统通知",
        ["TrayBlink"] = "托盘图标闪烁提醒",
        ["QuietHours"] = "静音时段",
        ["QuietHoursEnabled"] = "启用静音时段",
        ["QuietStart"] = "开始",
        ["QuietEnd"] = "结束",
        ["SuppressFullscreen"] = "全屏应用运行时暂停系统通知",
        ["DeviceAlerts"] = "设备提醒",
        ["Alias"] = "自定义设备名称",
        ["AliasHint"] = "留空则使用设备原始名称。",
        ["OriginalName"] = "原始名称",
        ["Offline"] = "离线",
        ["Threshold"] = "阈值",
        ["LowBatteryThreshold"] = "低电量提醒阈值",
        ["FollowGlobalThreshold"] = "使用默认阈值",
        ["Pause"] = "暂停",
        ["PauseOneHour"] = "暂停 1 小时",
        ["PauseUntilNextLaunch"] = "暂停至下次启动",
        ["ResumeAlerts"] = "恢复提醒",
        ["TestNotification"] = "测试通知",
        ["TestBlink"] = "测试托盘图标闪烁",
        ["StopBlink"] = "停止闪烁",
        ["RestoreDefaults"] = "恢复默认",
        ["RemoveHistory"] = "忘记此设备",
        ["LastUpdate"] = "最后更新于",
        ["Battery"] = "电量",
        ["BatteryUnknown"] = "电量未知",
        ["BatteryStatusCharging"] = "充电中",
        ["BatteryStatusFull"] = "已充满",
        ["BatteryStatusNotCharging"] = "未充电",
        ["BatteryStatusDischarging"] = "放电中",
        ["BatteryStatusUnknown"] = "状态未知",
        ["NoDevices"] = "尚未发现受支持的 Logitech 设备。",
        ["Diagnostics"] = "诊断",
        ["ExportDiagnostics"] = "导出诊断",
        ["RefreshDiagnostics"] = "刷新",
        ["GHubStatus"] = "G Hub 正在运行",
        ["Port9010Status"] = "G Hub 本地服务可连接",
        ["CurrentLanguage"] = "当前语言",
        ["AlertSummary"] = "提醒配置摘要",
        ["Yes"] = "是",
        ["No"] = "否",
        ["LowBatteryTitle"] = "低电量提醒",
        ["LowBatteryBody"] = "{0} 电量为 {1:0}%。",
        ["TestNotificationTitle"] = "PowerTray 测试通知",
        ["TestNotificationBody"] = "{0} 的系统通知可用。",
        ["TestNotificationGenericBody"] = "系统通知可用。",
        ["SettingsLoadErrorTitle"] = "PowerTray - 设置加载错误",
        ["SettingsLoadErrorBody"] = "读取 appsettings.toml 失败，是否重置为默认配置？",
        ["DiagnosticsExported"] = "诊断已导出",
        ["DiagnosticsExportFailed"] = "诊断导出失败",
        ["CheckingUpdates"] = "正在检查更新…",
        ["AlreadyLatest"] = "PowerTray 已是最新版本。",
        ["UpdateAvailableTitle"] = "发现新版本",
        ["UpdateAvailableBody"] = "PowerTray {0} 已可下载。",
        ["UpdateAvailableDetail"] = "安装器会保存到你的下载目录。",
        ["DownloadingUpdate"] = "正在下载更新…",
        ["UpdateDownloadedTitle"] = "更新已下载",
        ["UpdateDownloadedBody"] = "PowerTray {0} 已下载完成。",
        ["UpdateDownloadedDetail"] = "保存位置：{0}",
        ["UpdateDownloadFailed"] = "更新下载失败",
        ["UpdateCheckFailed"] = "检查更新失败",
        ["HttpRemoteEnabledTitle"] = "远程 HTTP 访问已启用",
        ["HttpRemoteEnabledBody"] = "PowerTray 设备 API 已监听本机以外的连接。请妥善保护访问令牌，并使用防火墙限制该端口。",
        ["NoInstallerAsset"] = "最新发布中没有可下载的 PowerTray 安装器。",
        ["UpdateSignatureInvalid"] = "发布校验文件的签名无效。",
        ["UpdateChecksumInvalid"] = "发布校验文件缺少匹配的安装器文件名。",
        ["UpdateChecksumMismatch"] = "已下载的安装器与发布校验值不一致。",
        ["DownloadUpdate"] = "下载",
        ["RunInstaller"] = "运行安装器",
        ["OpenFolder"] = "打开文件夹",
        ["Cancel"] = "取消",
        ["OK"] = "确定",
        ["Details"] = "详细信息",
        ["Never"] = "从未",
        ["Available"] = "可用",
        ["Unavailable"] = "不可用",
        ["DiagnosticsTitle"] = "PowerTray 诊断",
        ["DiagnosticsGenerated"] = "生成时间",
        ["DiagnosticsDevices"] = "设备",
        ["RecognizedDevices"] = "已识别设备",
        ["NativeDiagnostics"] = "原生后端诊断：{0}",
        ["NativeDiagnosticsError"] = "原生后端诊断错误：{0}",
        ["HidNoResponse"] = "PowerTrayHID 未在诊断超时前响应。",
        ["HidJsonParseFailed"] = "PowerTrayHID 返回的诊断 JSON 无法解析。",
        ["VersionPrefix"] = "PowerTray 版本",
        ["ReleaseVersion"] = "当前安装版本",
        ["PausedUntil"] = "暂停至 {0}",
        ["PausedUntilNextLaunch"] = "暂停至下次启动",
    };

    private static readonly IReadOnlyDictionary<string, string> JaJp = new Dictionary<string, string>
    {
        ["ProductName"] = "PowerTray",
        ["MenuDevices"] = "デバイス",
        ["MenuRediscover"] = "デバイスを再スキャン",
        ["MenuNumericIcon"] = "数値バッテリーアイコンを表示",
        ["MenuAutoStart"] = "Windows 起動時に開始",
        ["MenuSettings"] = "設定",
        ["MenuCheckUpdates"] = "アップデートを確認",
        ["MenuExit"] = "終了",
        ["SettingsTitle"] = "PowerTray 設定",
        ["NavGeneral"] = "一般",
        ["NavAlerts"] = "通知",
        ["NavDevices"] = "デバイス",
        ["NavDiagnostics"] = "診断",
        ["Language"] = "言語",
        ["English"] = "英語",
        ["Chinese"] = "簡体字中国語",
        ["Japanese"] = "日本語",
        ["Theme"] = "テーマ",
        ["ThemeSystem"] = "システム設定に合わせる",
        ["ThemeLight"] = "ライト",
        ["ThemeDark"] = "ダーク",
        ["UiScale"] = "表示サイズ",
        ["UiScaleSmall"] = "小",
        ["UiScaleStandard"] = "標準",
        ["UiScaleLarge"] = "大",
        ["UiScaleMaximum"] = "最大",
        ["StartWithWindows"] = "Windows 起動時に開始",
        ["AutoCheckUpdates"] = "アップデートを自動確認",
        ["NumericIcon"] = "トレイアイコンにバッテリー残量を表示",
        ["TrayToolTipDisplay"] = "トレイのホバー表示",
        ["TrayToolTipModeDisabled"] = "ホバー表示を無効にする",
        ["TrayToolTipModeWindowsNative"] = "Windows ネイティブ表示",
        ["TrayToolTipModePowerTrayCustom"] = "PowerTray カスタム表示",
        ["TrayToolTipDescription"] = "Windows ネイティブ表示はシステムトレイによって管理され、外観と表示時間は Windows の設定に従います。PowerTray カスタム表示はアプリのテーマと完全な情報表示に対応します。表示方式の切り替えにはトレイアイコンの再作成が必要なため、PowerTray の再起動後に反映されます。",
        ["TrayToolTipRestartPending"] = "再起動後に反映",
        ["TrayToolTipRestartTitle"] = "PowerTray の再起動が必要です",
        ["TrayToolTipRestartBody"] = "トレイのホバー表示モードは、トレイアイコンを再作成した後に反映されます。PowerTray を今すぐ再起動しますか？",
        ["TrayToolTipRestartDetail"] = "ネイティブ表示は Windows Shell が管理し、カスタム表示は WPF Popup が管理します。再起動すると、以前のトレイ登録、Popup、イベント購読を完全に解除でき、表示の重複や画面左上への残留を防げます。",
        ["RestartNow"] = "今すぐ再起動",
        ["RestartLater"] = "後で再起動",
        ["RestartFailedTitle"] = "PowerTray の再起動に失敗しました",
        ["RestartFailedBody"] = "新しい PowerTray プロセスを起動できませんでした。現在の PowerTray はそのまま実行され、保存した表示モードは次回の通常起動時に反映されます。",
        ["FollowGlobalNumericIcon"] = "全体のトレイ表示設定を使用",
        ["ConfirmForgetDeviceTitle"] = "このデバイスを忘れますか？",
        ["ConfirmForgetDeviceBody"] = "{0} の保存済み設定と履歴を削除します。続行しますか？",
        ["GlobalDefaults"] = "既定の通知設定",
        ["DefaultThreshold"] = "低バッテリー通知の既定しきい値",
        ["WindowsNotification"] = "Windows 通知",
        ["TrayBlink"] = "トレイアイコンを点滅",
        ["QuietHours"] = "通知しない時間帯",
        ["QuietHoursEnabled"] = "通知しない時間帯を有効にする",
        ["QuietStart"] = "開始",
        ["QuietEnd"] = "終了",
        ["SuppressFullscreen"] = "全画面アプリの使用中は Windows 通知を一時停止",
        ["DeviceAlerts"] = "デバイス通知",
        ["Alias"] = "カスタムデバイス名",
        ["AliasHint"] = "空欄のままにするとデバイス本来の名前を使います。",
        ["OriginalName"] = "元の名前",
        ["Offline"] = "オフライン",
        ["Threshold"] = "しきい値",
        ["LowBatteryThreshold"] = "低バッテリー通知しきい値",
        ["FollowGlobalThreshold"] = "既定のしきい値を使用",
        ["Pause"] = "一時停止",
        ["PauseOneHour"] = "1 時間停止",
        ["PauseUntilNextLaunch"] = "次回起動まで停止",
        ["ResumeAlerts"] = "通知を再開",
        ["TestNotification"] = "通知をテスト",
        ["TestBlink"] = "点滅をテスト",
        ["StopBlink"] = "点滅を停止",
        ["RestoreDefaults"] = "既定に戻す",
        ["RemoveHistory"] = "このデバイスを忘れる",
        ["LastUpdate"] = "最終更新",
        ["Battery"] = "バッテリー",
        ["BatteryUnknown"] = "バッテリー不明",
        ["BatteryStatusCharging"] = "充電中",
        ["BatteryStatusFull"] = "満充電",
        ["BatteryStatusNotCharging"] = "充電していません",
        ["BatteryStatusDischarging"] = "放電中",
        ["BatteryStatusUnknown"] = "状態不明",
        ["NoDevices"] = "対応する Logitech デバイスはまだ見つかっていません。",
        ["Diagnostics"] = "診断",
        ["ExportDiagnostics"] = "診断をエクスポート",
        ["RefreshDiagnostics"] = "更新",
        ["GHubStatus"] = "G Hub の実行状態",
        ["Port9010Status"] = "G Hub ローカルサービスに接続可能",
        ["CurrentLanguage"] = "現在の言語",
        ["AlertSummary"] = "通知設定の概要",
        ["Yes"] = "はい",
        ["No"] = "いいえ",
        ["LowBatteryTitle"] = "バッテリー残量が低下しています",
        ["LowBatteryBody"] = "{0} のバッテリー残量は {1:0}% です。",
        ["TestNotificationTitle"] = "PowerTray テスト通知",
        ["TestNotificationBody"] = "{0} の Windows 通知は利用できます。",
        ["TestNotificationGenericBody"] = "Windows 通知は利用できます。",
        ["SettingsLoadErrorTitle"] = "PowerTray - 設定エラー",
        ["SettingsLoadErrorBody"] = "appsettings.toml を読み込めませんでした。既定値に戻しますか？",
        ["DiagnosticsExported"] = "診断をエクスポートしました",
        ["DiagnosticsExportFailed"] = "診断のエクスポートに失敗しました",
        ["CheckingUpdates"] = "アップデートを確認しています...",
        ["AlreadyLatest"] = "PowerTray は最新です。",
        ["UpdateAvailableTitle"] = "アップデートがあります",
        ["UpdateAvailableBody"] = "PowerTray {0} をダウンロードできます。",
        ["UpdateAvailableDetail"] = "インストーラーはダウンロードフォルダーに保存されます。",
        ["DownloadingUpdate"] = "アップデートをダウンロードしています...",
        ["UpdateDownloadedTitle"] = "ダウンロードが完了しました",
        ["UpdateDownloadedBody"] = "PowerTray {0} のダウンロードが完了しました。",
        ["UpdateDownloadedDetail"] = "保存先: {0}",
        ["UpdateDownloadFailed"] = "アップデートをダウンロードできませんでした",
        ["UpdateCheckFailed"] = "アップデートを確認できませんでした",
        ["HttpRemoteEnabledTitle"] = "リモート HTTP アクセスが有効です",
        ["HttpRemoteEnabledBody"] = "PowerTray のデバイス API はこの PC 以外からも接続できます。アクセストークンを保護し、ファイアウォールでポートを制限してください。",
        ["NoInstallerAsset"] = "最新リリースに PowerTray インストーラーが含まれていません。",
        ["UpdateSignatureInvalid"] = "リリースのチェックサム署名が無効です。",
        ["UpdateChecksumInvalid"] = "リリースのチェックサムに一致するインストーラー名がありません。",
        ["UpdateChecksumMismatch"] = "ダウンロードしたインストーラーがリリースのチェックサムと一致しません。",
        ["DownloadUpdate"] = "ダウンロード",
        ["RunInstaller"] = "インストーラーを実行",
        ["OpenFolder"] = "フォルダーを開く",
        ["Cancel"] = "キャンセル",
        ["OK"] = "OK",
        ["Details"] = "詳細",
        ["Never"] = "なし",
        ["Available"] = "利用可能",
        ["Unavailable"] = "利用不可",
        ["DiagnosticsTitle"] = "PowerTray 診断",
        ["DiagnosticsGenerated"] = "生成日時",
        ["DiagnosticsDevices"] = "デバイス",
        ["RecognizedDevices"] = "認識済みデバイス",
        ["NativeDiagnostics"] = "ネイティブ診断: {0}",
        ["NativeDiagnosticsError"] = "ネイティブ診断エラー: {0}",
        ["HidNoResponse"] = "診断タイムアウトまでに PowerTrayHID が応答しませんでした。",
        ["HidJsonParseFailed"] = "PowerTrayHID が返した診断 JSON を解析できませんでした。",
        ["VersionPrefix"] = "PowerTray バージョン",
        ["ReleaseVersion"] = "インストール済みバージョン",
        ["PausedUntil"] = "{0} まで停止",
        ["PausedUntilNextLaunch"] = "次回起動まで停止",
    };

}
